theme: jekyll-theme-minimal
title: Andie Creel - Environmental Economist
description: Job market candidate in Environmental Economics at Yale. Research on urban green space, recreation, and natural capital accounting.