theme: minima

# Include the CSS file
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'styles.css'
title: "Andie M Creel - Economist"
description: "Environmental Economics PhD Candidate | Job Market 2025/2026"