theme: jekyll-theme-minimal
title: Andie M. Creel

# Add navigation links
header_pages:
  - index.md
  - research.md
  - teaching_statement.md
  - contact.md
  - new_page.md  # Add your new Markdown file here
